// lib/capabilities/map.ts
// The capability map (#82) — the single source for what the platform can do.
// Owner rule: nothing may live in the database without being callable, and
// both sides must be documented. From this one list:
//   docs/BACKEND-API-GUIDE.md   capability → database objects → endpoints → rules
//   docs/FRONTEND-DATA-GUIDE.md page → section → the data and actions it can use
// are generated (npm run docs:capabilities), and tests/integration/
// capability-coverage.test.ts fails if a table, view, function or route is
// missing here, if the contract and the routes disagree, or if the guides are
// stale. Not imported by the running app.

export type Audience = "public" | "admin";

export interface Capability {
  id: string;
  title: string;
  audience: Audience;
  /** What it is and why it exists, in a sentence or two. */
  summary: string;
  /** Tables, views and functions it reads or writes. */
  db: string[];
  /** "METHOD /path" as in openapi-contract.yaml (paths relative to /api/v1). */
  endpoints: string[];
  /** Business rules it enforces or depends on. */
  rules: string[];
  /** Where it belongs in the UI: page path → section. "(proposed)" = no page yet. */
  frontend: { page: string; section: string }[];
  /** What a frontend must get right when using it. */
  notes: string[];
}

export const CAPABILITIES: Capability[] = [
  // ============================ PUBLIC ============================
  {
    id: "profile",
    title: "Owner profile and links",
    audience: "public",
    summary: "Who the owner is — name, headline, role, location, contact, summary, bio, availability, building-since year, social links, and the organizations founded or co-founded. All admin-edited data.",
    db: ["PublicProfile", "PublicProfileLink", "PublicAffiliation", "PublicProfileTitle", "PublicProfilePhoto"],
    endpoints: ["GET /profile", "GET /profile/photo/{purpose}"],
    rules: [],
    frontend: [
      { page: "(every page)", section: "Header name, footer contact and social links" },
      { page: "/", section: "Hero: name, headline" },
      { page: "/about", section: "Bio, availability, location, building since" },
      { page: "/contact", section: "Email, phone (only when set), links" },
    ],
    notes: [
      "Never hardcode owner details — read them here (owner's rule).",
      "phone, bio, availability and summary may be null: render nothing, not a placeholder.",
      "links[].kind names the brand icon (github, linkedin, whatsapp, …).",
      "titles[] are the owner's current titles and qualifications, in order — show them together wherever the name appears; never type a title into a page (F5c, D13).",
      "photos.{purpose} gives a cache-safe url, alt text and size — use it with next/image; a missing purpose means no photo yet: render nothing (BR-1.17).",
    ],
  },
  {
    id: "homes",
    title: "GitHub homes",
    audience: "public",
    summary: "The organisations the owner's repositories live under — their own account and their ventures — each with role, GitHub accounts and how many published systems it holds (F5c, D12).",
    db: ["PublicHome", "OrganizationKind", "PublicSystemHome"],
    endpoints: ["GET /homes"],
    rules: ["BR-1.4", "BR-1.13"],
    frontend: [
      { page: "(every page)", section: "Footer: the three homes with their system counts" },
      { page: "/", section: "System map: homes → systems → technologies" },
      { page: "/organizations/[slug] (proposed)", section: "One page per home" },
    ],
    notes: ["Counts come from the database and never include a draft, a scheduled system or an unnamed client (BR-1.4)."],
  },
  {
    id: "lenses",
    title: "Visitor lenses",
    audience: "public",
    summary: "The lenses a visitor picks to frame the site and the AI guide — I'm hiring, I have a project, I'm an engineer, just exploring — in the owner's order (Constitution §4).",
    db: ["PublicVisitorLens"],
    endpoints: ["GET /lenses"],
    rules: [],
    frontend: [{ page: "/", section: "Hero: lens chips" }, { page: "(every page)", section: "AI guide: opening chips" }],
    notes: ["Key and label only — the framing prompt and priority content stay private (they are the guide's instructions)."],
  },
  {
    id: "github",
    title: "Public GitHub work",
    audience: "public",
    summary: "Every public repo in the owner's homes — from the day it began — with languages, topics, stars, activity and README excerpt, and the last 90 days of commits. Refreshed by the daily GitHub sync; private, archived and client-restricted repos never appear (F5c).",
    db: ["PublicGithubRepo", "PublicRepoCommit", "RepoCommit"],
    endpoints: ["GET /github/repos", "GET /github/commits"],
    rules: ["BR-1.3", "BR-1.4", "BR-1.7"],
    frontend: [
      { page: "(every page)", section: "AI guide: its GitHub knowledge" },
      { page: "/systems", section: "Each card: languages and last push" },
      { page: "/systems/[slug]", section: "At a glance: languages and topics; proof strip: started, last push, commits this year; latest commits" },
      { page: "/now (proposed)", section: "What's changing: recent commits and active repos" },
    ],
    notes: ["The sync stores a README and commits for public repos only, and wipes them if a repo turns private."],
  },
  {
    id: "activity",
    title: "Weekly build activity",
    audience: "public",
    summary: "Commits per week for each published system over the last 26 weeks — counts only, from the daily GitHub sync (F5c).",
    db: ["PublicSystemActivity"],
    endpoints: ["GET /activity"],
    rules: ["BR-1.1", "BR-1.13"],
    frontend: [
      { page: "/", section: "Selected work: a sparkline on each system" },
      { page: "/systems", section: "Each card: a 26-week sparkline and a live marker when it moved this month" },
      { page: "/systems/[slug]", section: "Activity: 26 weeks of commits as bars" },
      { page: "/now (proposed)", section: "What's moving this week" },
    ],
    notes: ["Only systems that are live on the site; no commit content, no authors."],
  },
  {
    id: "guide",
    title: "The AI guide",
    audience: "public",
    summary: "The owner's AI guide: answers visitors from the site's public data, cites the page each fact came from, and can open a page, search the site or draft the contact form for the visitor to send — each tool behind its own flag (Constitution §6, PUBLIC-REDESIGN-PLAN §3a).",
    db: ["PublicFlag", "VisitorLens"],
    endpoints: ["POST /guide"],
    rules: ["BR-2.4", "BR-4.1", "BR-4.2", "BR-4.3", "BR-4.4", "BR-4.6"],
    frontend: [
      { page: "/", section: "Hero: the character, greeting and lens chips" },
      { page: "(every page)", section: "Docked launcher and the chat panel" },
      { page: "/contact", section: "A draft from the guide, for the visitor to review and send" },
    ],
    notes: [
      "Off unless concierge.enabled is on; every limit (model, questions per conversation and per visitor, daily cap, answer length, context budget) is a concierge.* setting.",
      "Grounded only in the public views, read through the public role; the lens framing prompt is read server-side and never sent to the browser.",
    ],
  },
  {
    id: "platform.pulse",
    title: "Platform pulse",
    audience: "public",
    summary: "The platform reporting on itself — business rules the database enforces (counted from its own constraints, triggers and functions), audit events, the last successful job and GitHub sync, the running build (F5c §3.2).",
    db: ["PublicPlatformPulse", "ActivityLog", "JobRun"],
    endpoints: ["GET /platform/pulse"],
    rules: ["BR-3.4"],
    frontend: [{ page: "/", section: "Control room" }, { page: "(every page)", section: "Footer status line" }],
    notes: ["Aggregates only — no rows, no actors. deployment is null outside Vercel."],
  },
  {
    id: "home",
    title: "Homepage",
    audience: "public",
    summary: "Everything the homepage shows in one call: the live ledger, the admin's homepage picks, the published-systems count and the admin-approved numbers.",
    db: ["PublicLedger", "PublicSystem", "PublicMetric"],
    endpoints: ["GET /home"],
    rules: ["BR-1.1", "BR-5.3"],
    frontend: [
      { page: "/", section: "Hero ledger (years building, organizations founded, shipped / in progress / queued)" },
      { page: "/", section: "Featured work (the admin's picks, in order)" },
      { page: "/", section: "Control room: approved figures (approved metrics only)" },
    ],
    notes: [
      "Ledger counts are live content facts; metrics are curated snapshots — label them differently (BR-5.3).",
      "featured falls back to flagship-first until the admin picks some; never empty while anything is published.",
    ],
  },
  {
    id: "content",
    title: "Page content blocks",
    audience: "public",
    summary: "Admin-edited site copy by key — e.g. how-i-build: the mission statement and governing principles (#106).",
    db: ["PublicSiteContent"],
    endpoints: ["GET /content/{key}"],
    rules: [],
    frontend: [
      { page: "/method", section: "Mission and principles" },
      { page: "/", section: "Principles band" },
    ],
    notes: ["404 for an unknown or empty block — hide the section rather than showing placeholder copy."],
  },
  {
    id: "systems.catalog",
    title: "Systems catalog",
    audience: "public",
    summary: "Published systems with filters by organization, domain, status and flagship; the organizations list for the filter shows only names that are disclosed.",
    db: ["PublicSystem", "PublicOrganization", "Status", "Domain"],
    endpoints: ["GET /systems", "GET /organizations"],
    rules: ["BR-1.1", "BR-1.3", "BR-1.4", "BR-1.7"],
    frontend: [{ page: "/systems", section: "Grid, filters, pagination" }],
    notes: [
      "organization may be a masked label (\"a fintech client\") — show it as text, never link it.",
      "repoPrivate = true means repoUrl is null: show a private-repository lock and a Request access action (to /contact).",
      "Status colour comes from statusColorToken — never map status keys to colours in code (EXT-1).",
    ],
  },
  {
    id: "systems.caseStudy",
    title: "Case study",
    audience: "public",
    summary: "One published system in full — case study body, measured impacts, permitted testimonials — and related systems in the same domain.",
    db: ["PublicSystem", "PublicImpact", "PublicTestimonial", "PublicSlugRedirect", "PublicSystemScreenshot"],
    endpoints: ["GET /systems/{slug}", "GET /systems/{slug}/related", "GET /systems/{slug}/screenshot"],
    rules: ["BR-1.1", "BR-1.3", "BR-1.4", "BR-1.7", "BR-6.1", "BR-6.2", "BR-1.14", "BR-4.5"],
    frontend: [
      { page: "/systems/[slug]", section: "Header, case study body, impacts, testimonials" },
      { page: "/systems/[slug]", section: "Who wrote the case study: an \"AI\" label when it was written from the repo" },
      { page: "/systems/[slug]", section: "The screenshot of the live site, in a browser frame" },
      { page: "/", section: "Selected work: each system's screenshot" },
      { page: "/systems/[slug]", section: "Related systems" },
    ],
    notes: [
      "An unknown or unpublished slug is a plain 404 — never a \"private\" message (BR-1.3/1.4).",
      "liveUrl/screenshotUrl are null for NDA work: render a neutral placeholder.", "An old slug answers with a permanent redirect (308) to the current one — follow it; links from before a rename keep working (BR-1.14).", "caseStudyAuthor = ai means the case study was written by AI from the public repo (BR-4.5): label it, with caseStudyWrittenAt.", "screenshotUrl points at /systems/{slug}/screenshot?v=… when a screenshot is stored (captured or uploaded, BR-1.18) — the link is immutable; never present for NDA work."],
  },
  {
    id: "search",
    title: "Instant search",
    audience: "public",
    summary: "Full-text and typo-tolerant search over published systems, journey entries and skills — never hidden work, because it reads the public views only.",
    db: ["search_public", "rate_limit_hit"],
    endpoints: ["GET /search"],
    rules: ["BR-1.1", "BR-1.4"],
    frontend: [{ page: "(every page)", section: "⌘K search palette" }],
    notes: [
      "Results: kind (system → /systems/{key}, journey → /journey#{key}, skill), title, subtitle.",
      "Debounce typing; 429 means slow down (limits are admin settings search.rateLimit.*).",
      "Queries under 2 characters are refused — don't send them.",
    ],
  },
  {
    id: "journey",
    title: "Journey",
    audience: "public",
    summary: "The published timeline — education, roles, launches, achievements — filterable by milestone type. Entries about a system appear only while it's published.",
    db: ["PublicTimeline", "MilestoneType"],
    endpoints: ["GET /timeline"],
    rules: ["BR-1.12"],
    frontend: [{ page: "/journey", section: "Timeline and type filter" }],
    notes: ["Filter options come from GET /lookups/milestone-type."],
  },
  {
    id: "skills",
    title: "Skills with evidence",
    audience: "public",
    summary: "Every skill with what proves it: published systems that use it, roles and published study — strongest first.",
    db: ["SkillEvidence", "Skill", "SkillCategory"],
    endpoints: ["GET /skills"],
    rules: ["BR-1.1"],
    frontend: [
      { page: "/cv", section: "Skills" },
      { page: "/about", section: "What I work with" },
      { page: "/systems/[slug]", section: "Skills this system proves (match systemSlugs)" },
    ],
    notes: ["Show evidence, not self-rating: \"used in 3 systems, 2 roles\" beats a bar chart."],
  },
  {
    id: "achievements",
    title: "Certifications and awards",
    audience: "public",
    summary: "Published achievements; one about a system shows only while that system is published.",
    db: ["PublicAchievement"],
    endpoints: ["GET /achievements"],
    rules: [],
    frontend: [
      { page: "/about", section: "Certifications and awards" },
      { page: "/cv", section: "Certifications" },
    ],
    notes: ["systemSlug links an achievement to its case study when present."],
  },
  {
    id: "metrics",
    title: "Curated numbers",
    audience: "public",
    summary: "The admin-approved statistics (\"By the numbers\"). A computed or entered value is never public until approved.",
    db: ["PublicMetric"],
    endpoints: ["GET /metrics"],
    rules: ["BR-5.3"],
    frontend: [
      { page: "/", section: "Control room: approved figures" },
      { page: "/about", section: "By the numbers" },
    ],
    notes: ["Show approvedAt as \"as of\" — these are point-in-time figures."],
  },
  {
    id: "cv",
    title: "CV — the options, view and download",
    audience: "public",
    summary:
      "Two clearly labelled CV options (#92): the CV generated from live data — as data for on-screen rendering and as identical ATS-safe PDF or Word files, optionally tailored to a target role — and the owner's uploaded CV file. Each is offered only while the admin shows it.",
    db: [
      "PublicCvOption",
      "PublicCvUpload",
      "PublicExperience",
      "PublicEducation",
      "PublicAchievement",
      "PublicProfile",
      "PublicProfileLink",
      "SkillEvidence",
      "DocumentGen",
      "rate_limit_hit",
    ],
    endpoints: ["GET /cv/options", "GET /cv", "POST /cv/generate", "GET /cv/documents/{id}", "GET /cv/uploads/{id}"],
    rules: ["BR-7.1", "BR-7.2", "BR-7.3", "BR-7.4", "BR-7.5", "BR-7.6"],
    frontend: [
      { page: "/cv", section: "CV options (GET /cv/options), in the order given, each with its label and note; the uploaded one shows its upload date" },
      { page: "/cv", section: "On-screen CV, target-role box, Download PDF / Word — only while the generated option is listed" },
    ],
    notes: [
      "Start from GET /cv/options: show exactly those options, in that order, with their labels — never assume either exists.",
      "Never present one option as the other: the uploaded CV is the owner's file as uploaded; the generated one is live data (BR-7.1).",
      "Render GET /cv exactly — it's the same model the generated files come from. It, generate and document downloads are 404 while the generated option is hidden.",
      "POST /cv/generate returns a fileUrl; navigate to it to download. Uploaded files are plain links (files[].url). 429 = rate-limited.",
    ],
  },
  {
    id: "inquiries.submit",
    title: "Let's Talk — send a message",
    audience: "public",
    summary: "The single visitor write path (docs/LETS-TALK-SPEC.md): a category and kind, a form shaped to it, PDFs checked by their bytes; honeypot, signed form token, per-connection and per-address limits, payload-bound idempotency; a reference back; email queued in the same transaction.",
    db: ["Inquiry", "InquiryType", "InquirySubtype", "InquiryMeeting", "InquiryDocument", "Notification", "rate_limit_hit", "new_inquiry_reference"],
    endpoints: ["POST /inquiries", "GET /inquiries/form", "GET /inquiries/types"],
    rules: ["BR-2.2", "BR-2.3", "BR-2.4", "BR-2.5", "BR-2.6", "BR-2.7", "LT-1", "LT-2", "LT-3", "LT-4", "LT-5", "LT-8", "LT-9", "LT-10", "LT-12", "LT-13"],
    frontend: [
      { page: "/contact", section: "What brings you here? — the category tiles (GET /inquiries/types)" },
      { page: "/contact", section: "The form shaped to the category, and the confirmation with its reference" },
      { page: "/", section: "Let's talk band: each category opens /contact?about=<key>" },
    ],
    notes: [
      "Fetch GET /inquiries/form when the form is shown and send its token as formToken; include the hidden honeypot field \"website\" (the visitor's own site is organizationWebsite).",
      "Send an idempotencyKey (uuid), kept across retries, so a double-submit returns the original confirmation.",
      "The review promise comes from the inquiry.reviewSlaHours setting — don't hardcode \"48 hours\".",
      "Show the reference from the response; it identifies the message, it never unlocks anything.",
    ],
  },
  {
    id: "lookups",
    title: "Lookups — statuses, domains, types, categories, relationships",
    audience: "public",
    summary: "Every open list the platform uses, read publicly for filters and forms; created, edited and deprecated by the admin without code changes.",
    db: ["Status", "Domain", "InquiryType", "MilestoneType", "SkillCategory", "RepoRelationship", "TitleKind", "OrganizationKind"],
    endpoints: [
      "GET /lookups/{type}",
      "POST /lookups/{type}",
      "PATCH /lookups/{type}/{id}",
      "POST /lookups/{type}/{id}/deprecate",
    ],
    rules: ["EXT-1", "BR-8.1", "BR-8.2", "BR-8.3", "BR-1.11"],
    frontend: [
      { page: "/systems", section: "Status and domain filters" },
      { page: "/contact", section: "Inquiry type select" },
      { page: "/admin/settings", section: "Lookups: add, rename, re-stage, recolour, deprecate" },
    ],
    notes: ["409 LOOKUP_KEY_DEPRECATED means offer \"reactivate\" instead of creating again (BR-8.3)."],
  },

  // ============================ ADMIN ============================
  {
    id: "admin.auth",
    title: "Admin sign-in (password + 2FA)",
    audience: "admin",
    summary: "Password then TOTP or recovery code; lockout, timing-safe, every attempt audited.",
    db: ["AdminUser", "LoginChallenge", "RateLimitEntry", "ActivityLog", "rate_limit_hit"],
    endpoints: [
      "POST /admin/auth/login",
      "POST /admin/auth/verify-2fa",
      "POST /admin/auth/logout",
      "POST /admin/auth/change-password",
      "GET /admin/auth/recovery-codes",
      "POST /admin/auth/recovery-codes",
    ],
    rules: ["BR-3.1", "BR-3.2", "BR-3.4", "BR-3.5", "BR-3.6", "BR-3.8", "BR-3.9", "BR-3.10", "BR-3.11", "BR-3.12", "BR-3.14", "BR-3.15"],
    frontend: [
      { page: "/admin/login", section: "Password step, 2FA step, recovery-code option" },
      { page: "/admin/account", section: "Change password; recovery codes — remaining count, low-count notice, regenerate (show the ten codes once)" },
    ],
    notes: ["Show neutral copy on expiry (\"session ended\"), not an error.", "Sign-out (POST /admin/auth/logout) ends every session, not just this browser's.", "Password rotation (BR-3.15) needs the current password and a live TOTP code; it ends every prior session. On `SESSION_REVOKED` send the admin back to sign in.", "Show ACCOUNT_LOCKED with its lockedUntil countdown — lockouts grow with repeated failures (BR-3.2).", "Regenerated recovery codes are in that one response only — make the admin save them before leaving (BR-3.12).", "Mutations must come from this site's own pages; a 403 CSRF_REJECTED means a cross-site request (BR-3.9)."],
  },
  {
    id: "admin.overview",
    title: "Admin dashboard",
    audience: "admin",
    summary: "What needs attention now — overdue inquiries, systems to curate, repo-owner permissions outstanding, journey drafts and number proposals awaiting a decision, CV gaps — plus pipeline, jobs and audit activity.",
    db: ["Inquiry", "System", "Timeline", "MetricSnapshot", "JobRun", "ActivityLog", "PublicLedger"],
    endpoints: ["GET /admin/overview"],
    rules: ["BR-2.2", "BR-1.8", "BR-1.11", "BR-1.12", "BR-5.3"],
    frontend: [{ page: "/admin", section: "Attention list, pipeline, CV score, jobs, recent activity" }],
    notes: ["Each attention count links to its screen, filtered (e.g. /admin/inquiries?overdue=true)."],
  },
  {
    id: "admin.systems",
    title: "Systems — curate, publish, feature",
    audience: "admin",
    summary: "Every system unmasked: edit everything but the slug, publish under BR-1.1/1.11, feature on the homepage, include on the CV, set skills and impacts; see status history, pace and weekly GitHub activity.",
    db: ["System", "Impact", "SkillOnSystem", "SystemStatusChange", "SystemPace", "SystemActivityWeek", "RepoRelationship", "Testimonial", "SystemSlugHistory", "SystemContentRevision", "SystemScreenshot"],
    endpoints: [
      "GET /admin/systems",
      "POST /admin/systems",
      "GET /admin/systems/{id}",
      "PATCH /admin/systems/{id}",
      "PUT /admin/systems/{id}/skills",
      "GET /admin/systems/{id}/impacts",
      "POST /admin/systems/{id}/impacts",
      "PATCH /admin/impacts/{id}",
      "DELETE /admin/impacts/{id}", "GET /admin/systems/{id}/revisions", "POST /admin/systems/{id}/revisions/{revisionId}/restore", "POST /admin/systems/{id}/writeup", "GET /admin/systems/{id}/screenshot", "POST /admin/systems/{id}/screenshot", "POST /admin/systems/{id}/screenshot/capture", "POST /admin/systems/{id}/screenshot/automatic"],
    rules: ["BR-1.1", "BR-1.2", "BR-1.8", "BR-1.9", "BR-1.10", "BR-1.11", "BR-1.12", "BR-1.13", "BR-1.14", "BR-1.15", "BR-4.5"],
    frontend: [
      { page: "/admin/systems", section: "List with curation queue, filters" },
      { page: "/admin/systems/[id]", section: "Editor, publish controls, homepage + CV placement, repo ownership" },
      { page: "/admin/systems/[id]", section: "Skills, impacts, status history, pace, activity chart" }, { page: "/admin/systems/[id]", section: "Revision history for the case study and description: versions with who and when, restore" }, { page: "/admin/systems/[id]", section: "Who wrote the summary and case study (you / AI from the repo), Regenerate from repo" }, { page: "/admin/systems/[id]", section: "Screenshot: the current one and where it came from; Upload, Capture now, Back to automatic" }],
    notes: [
      "409 CLIENT_APPROVAL_REQUIRED / OWNER_PERMISSION_REQUIRED: show the reason and the switch that fixes it.",
      "Systems are never deleted — offer Archive (BR-1.9).",
      "Testimonials are read-only here until V1.1.", "Scheduling (BR-1.13): send contentStatus published with a future publishAt — every publish gate is checked now, and it goes live at that time on its own. Show scheduled items with their time; a publishAt on unpublished content is a 400.", "Renaming (PATCH slug) keeps the old URL as a permanent redirect; the detail lists previousSlugs. 409 SLUG_TAKEN / SLUG_RESERVED — show the message.", "Every case-study and description edit is kept (BR-1.15); restoring records a new version — nothing is ever overwritten.", "writeup.descriptionSource / caseStudySource (BR-4.5): sync, generated (AI from the repo) or owner. Saving an edit makes a field the owner's, and the database then refuses any generated write over it. POST …/writeup hands both back to the AI and rewrites them now — 409 WRITEUPS_OFF / NOT_ELIGIBLE, 502 WRITEUP_FAILED, 503 WRITEUPS_UNAVAILABLE: show the message."],
  },
  {
    id: "admin.organizations",
    title: "Organizations",
    audience: "admin",
    summary: "The organizations systems belong to — ventures founded, clients, the owner's own — with their kind (a lookup) and GitHub logins for the sync.",
    db: ["Organization", "OrganizationKind"],
    endpoints: ["GET /admin/organizations", "POST /admin/organizations", "PATCH /admin/organizations/{id}"],
    rules: ["BR-1.2", "BR-1.4"],
    frontend: [{ page: "/admin/organizations", section: "List and editor" }],
    notes: ["isClient only affects systems created afterwards (BR-1.2) — say so next to the switch."],
  },
  {
    id: "admin.inquiries",
    title: "Inquiries — Let's Talk management",
    audience: "admin",
    summary: "The inbox (search, status, category, priority, overdue, possible duplicates) and each inquiry in full: the guarded workflow with its database-written history, private notes apart from what the applicant is told, information requests, meetings with their own time zone, PDFs, and the email outbox with retry; the kinds within each category.",
    db: ["Inquiry", "InquiryStatusChange", "InquiryNote", "InquiryMessage", "InquiryMeeting", "InquiryDocument", "Notification", "InquirySubtype"],
    endpoints: [
      "GET /admin/inquiries",
      "GET /admin/inquiries/{id}",
      "PATCH /admin/inquiries/{id}",
      "POST /admin/inquiries/{id}/notes",
      "POST /admin/inquiries/{id}/messages",
      "POST /admin/inquiries/{id}/meetings",
      "PATCH /admin/inquiries/{id}/meetings/{meetingId}",
      "GET /admin/inquiries/{id}/documents/{documentId}",
      "GET /admin/notifications",
      "POST /admin/notifications/{id}/retry",
      "GET /admin/inquiry-subtypes",
      "POST /admin/inquiry-subtypes",
      "PATCH /admin/inquiry-subtypes/{id}",
    ],
    rules: ["BR-2.1", "BR-2.2", "BR-5.5", "LT-5", "LT-6", "LT-7", "LT-10", "LT-11", "LT-12"],
    frontend: [
      { page: "/admin/inquiries", section: "Inbox: search, filters, overdue and duplicate flags, failed-email banner" },
      { page: "/admin/inquiries/[id]", section: "Workbench: status (stale-screen guard), priority, details, meetings, documents, messages, notes, history, emails" },
    ],
    notes: [
      "Offer only the moves in nextStatuses; send expectedVersion — 409 STALE means reload.",
      "internalReason is private; applicantMessage is what they were told — never mix them.",
    ],
  },
  {
    id: "admin.journey",
    title: "Journey — entries and approvals",
    audience: "admin",
    summary: "Write journey entries, and approve the ones the database drafts when a system first ships.",
    db: ["Timeline"],
    endpoints: ["GET /admin/timeline", "POST /admin/timeline", "PATCH /admin/timeline/{id}", "DELETE /admin/timeline/{id}"],
    rules: ["BR-1.12", "BR-1.13"],
    frontend: [{ page: "/admin/timeline", section: "Entries, auto-drafted queue (autoDrafted + draft), publish" }],
    notes: ["Publishing an auto-drafted entry is the approval.", "Scheduling (BR-1.13): send contentStatus published with a future publishAt — every publish gate is checked now, and it goes live at that time on its own. Show scheduled items with their time; a publishAt on unpublished content is a 400."],
  },
  {
    id: "admin.cv",
    title: "CV content, options, uploads, completeness and history",
    audience: "admin",
    summary:
      "Roles (with CV bullets, show/hide), education (expected graduation, coursework), skills; the owner's uploaded CV (versions, restore) and which CV options visitors see (#92); the completeness report with a suggested summary; every generated document.",
    db: ["Experience", "Education", "Skill", "SkillOnExperience", "SkillOnEducation", "DocumentGen", "CvUpload", "CvOptions"],
    endpoints: [
      "GET /admin/cv/experience",
      "POST /admin/cv/experience",
      "PATCH /admin/cv/experience/{id}",
      "DELETE /admin/cv/experience/{id}",
      "GET /admin/cv/education",
      "POST /admin/cv/education",
      "PATCH /admin/cv/education/{id}",
      "DELETE /admin/cv/education/{id}",
      "GET /admin/cv/skills",
      "POST /admin/cv/skills",
      "PATCH /admin/cv/skills/{id}",
      "DELETE /admin/cv/skills/{id}",
      "GET /admin/cv/check",
      "GET /admin/cv/documents",
      "GET /admin/cv/uploads",
      "POST /admin/cv/uploads",
      "GET /admin/cv/uploads/{id}",
      "POST /admin/cv/uploads/{id}/restore",
      "GET /admin/cv/options",
      "PATCH /admin/cv/options",
    ],
    rules: ["BR-7.1", "BR-7.2", "BR-7.3", "BR-7.4", "BR-7.5", "BR-7.6", "BR-1.13"],
    frontend: [
      { page: "/admin/cv", section: "Experience, Education, Skills tabs" },
      { page: "/admin/cv", section: "Completeness panel (score, issues, suggested summary, preview by target role)" },
      { page: "/admin/cv", section: "Generated documents" },
      { page: "/admin/cv", section: "Uploaded CV: upload (PDF/Word), versions with download and make-current" },
      { page: "/admin/cv", section: "What visitors can download: show/hide each option, which is first, labels and notes" },
    ],
    notes: [
      "Upload is multipart/form-data, field \"file\". 415 = not a PDF/Word file (or has macros), 413 = over cv.upload.maxMegabytes; show the message.",
      "CV options: show the database's BR-7.5 message on a 400 (e.g. hiding the generated CV before any upload).","The suggested summary is an offer: save it only through PATCH /admin/profile when the owner accepts.", "Scheduling (BR-1.13): send contentStatus published with a future publishAt — every publish gate is checked now, and it goes live at that time on its own. Show scheduled items with their time; a publishAt on unpublished content is a 400."],
  },
  {
    id: "admin.profile",
    title: "Profile, links and achievements",
    audience: "admin",
    summary: "The owner's details, social links (and which go on the CV), certifications and awards.",
    db: ["Profile", "ProfileLink", "Achievement", "ProfileTitle", "TitleKind", "ProfilePhoto"],
    endpoints: [
      "GET /admin/profile",
      "PATCH /admin/profile",
      "GET /admin/profile/photos",
      "POST /admin/profile/photos",
      "GET /admin/profile/photos/{id}",
      "PATCH /admin/profile/photos/{id}",
      "POST /admin/profile/photos/{id}/restore",
      "GET /admin/profile/titles",
      "POST /admin/profile/titles",
      "PATCH /admin/profile/titles/{id}",
      "DELETE /admin/profile/titles/{id}",
      "POST /admin/profile/links",
      "PATCH /admin/profile/links/{id}",
      "DELETE /admin/profile/links/{id}",
      "GET /admin/achievements",
      "POST /admin/achievements",
      "PATCH /admin/achievements/{id}",
      "DELETE /admin/achievements/{id}",
    ],
    rules: ["BR-1.13"],
    frontend: [{ page: "/admin/profile", section: "Profile form, links, achievements" }],
    notes: ["Achievements start as drafts; publishing puts them on the site and the CV.", "Scheduling (BR-1.13): send contentStatus published with a future publishAt — every publish gate is checked now, and it goes live at that time on its own. Show scheduled items with their time; a publishAt on unpublished content is a 400."],
  },
  {
    id: "admin.metrics",
    title: "Curated numbers — define, propose, decide",
    audience: "admin",
    summary: "Define metrics, enter values by hand or compute them from public data, and approve or reject each proposal; history is kept.",
    db: ["Metric", "MetricSnapshot", "propose_metric_snapshot", "approve_metric_snapshot", "JobRun"],
    endpoints: [
      "GET /admin/metrics",
      "POST /admin/metrics",
      "PATCH /admin/metrics/{key}",
      "POST /admin/metrics/{key}/proposals",
      "POST /admin/metrics/compute",
      "POST /admin/metrics/snapshots/{id}/approve",
      "POST /admin/metrics/snapshots/{id}/reject",
    ],
    rules: ["BR-5.3"],
    frontend: [{ page: "/admin/numbers", section: "Metrics, pending proposals with approve / reject, history" }],
    notes: ["A proposal's value can't be edited — enter a new one (the database refuses changes)."],
  },
  {
    id: "admin.settings",
    title: "Platform settings, feature flags, visitor lenses",
    audience: "admin",
    summary: "Admin-editable tunables with safe bounds (rate limits, review deadline, retention), feature flags, visitor lenses.",
    db: ["PlatformSetting", "Flag", "VisitorLens"],
    endpoints: [
      "GET /admin/settings/platform",
      "PATCH /admin/settings/platform/{key}",
      "GET /admin/settings/flags",
      "PATCH /admin/settings/flags/{key}",
      "GET /admin/settings/lenses",
      "POST /admin/settings/lenses",
      "PATCH /admin/settings/lenses/{id}",
    ],
    rules: ["BR-2.2", "BR-2.4", "BR-4.4", "BR-5.2"],
    frontend: [{ page: "/admin/settings", section: "Settings (with each one's rule and default), flags, lenses" }],
    notes: ["Show each setting's default and bounds; a reset is PATCHing the default value."],
  },
  {
    id: "admin.audit",
    title: "Audit trail",
    audience: "admin",
    summary: "Every change the database logged — who (admin / visitor / system), what changed column by column, when — filterable.",
    db: ["ActivityLog"],
    endpoints: ["GET /admin/activity-log"],
    rules: ["BR-3.4"],
    frontend: [{ page: "/admin/activity-log", section: "Log with filters (entity, action, actor, date range), before/after diff" }],
    notes: ["\"[redacted]\" marks a secret or personal field that's never stored in the log."],
  },
  {
    id: "admin.content",
    title: "Page content blocks",
    audience: "admin",
    summary:
      "Site copy that isn't tied to a system, role or the profile — the mission and principles, and whatever block comes next — as validated data the admin edits (#106).",
    db: ["SiteContent"],
    endpoints: ["GET /admin/content", "GET /admin/content/{key}", "PUT /admin/content/{key}"],
    rules: [],
    frontend: [{ page: "/admin/content", section: "One editor per block; save replaces the block" }],
    notes: [
      "Each key has a schema (lib/content/blocks.ts); a body that doesn't match is refused with the issues.",
      "An unknown key is 404 — a new block is one registry entry and one row, no migration.",
    ],
  },
  {
    id: "admin.freshness",
    title: "Freshness nudges",
    audience: "admin",
    summary:
      "Live content — systems, roles, education, the profile — that nobody has edited or reviewed for the admin's threshold, oldest first, with a one-click \"still accurate\" (#89).",
    db: ["stale_content", "System", "Experience", "Education", "Profile", "PlatformSetting"],
    endpoints: ["GET /admin/freshness", "POST /admin/freshness/{kind}/{id}/reviewed"],
    rules: ["BR-1.16"],
    frontend: [
      { page: "/admin", section: "Attention: stale content count (overview attention.staleContent)" },
      { page: "/admin/freshness", section: "Stale items oldest first — open to edit, or Mark reviewed" },
    ],
    notes: [
      "Only a real edit to what visitors see, or Mark reviewed, restarts the clock; GitHub sync updates don't (BR-1.16).",
      "The threshold is the setting content.freshnessDays (default 90).",
    ],
  },
  {
    id: "admin.jobs",
    title: "Scheduled jobs and their runs",
    audience: "admin",
    summary:
      "The registered jobs — retention and pruning, number proposals, the GitHub sync — run daily by the scheduler and on demand; every run's status, duration, summary, error and what started it (#94–#96).",
    db: ["JobRun", "apply_retention", "prune_expired", "SystemActivityWeek", "RateLimitEntry", "LoginChallenge"],
    endpoints: ["GET /admin/jobs", "POST /admin/jobs/{job}/run"],
    rules: ["BR-5.2", "BR-2.4", "BR-1.6", "BR-1.7", "BR-1.11", "BR-5.3"],
    frontend: [
      { page: "/admin/jobs", section: "Jobs with schedule and last run; runs by job, failures first; Run now" },
      { page: "/admin", section: "Last run per job (overview.jobs)" },
    ],
    notes: [
      "Run now answers 409 ALREADY_RUNNING while a run holds the lock; a failed run answers 500 with its recorded error.",
      "github.sync summaries list unmappedOwners (map them via an Organization's githubLogins), activityPending (GitHub still computing; retried next run) and accountErrors (an account that refused the token, with GitHub's reason — the other accounts still sync).",
    ],
  },
];

/** Database objects deliberately without an endpoint — each with the reason. */
export const NOT_EXPOSED: Record<string, string> = {
  Event: "Analytics events — collection starts with the consent banner (BR-5.1, F5).",
  ContentChunk: "AI concierge index — V1.1 (CLAUDE.md scope).",
  public_client_label: "Internal helper of the public views (BR-1.4 masking).",
  public_name_disclosed: "Internal helper of the public views (BR-1.4 masking).",
  is_live: "Internal helper of the public views: published and its publish time has come (BR-1.13).",
};
