-- F5c (docs/PUBLIC-REDESIGN-PLAN.md §6) — the data the redesigned public site
-- needs. Additive only.
--
-- 1. Titles and qualifications (D13). The owner is more than one title at a
--    time — "Software & AI Engineer" and "Final-year BSc Computer Science &
--    Mathematics student" — and the set changes (graduate, Honours, a new
--    role). A ProfileTitle row per title, its kind a lookup (EXT-1), dated so a
--    finished one leaves the public view on its own while staying on record.
-- 2. The three GitHub homes (D12). OrganizationKind (personal / venture /
--    client — a lookup) tells the owner's own account and ventures from
--    clients without code. PublicHome lists the organisations GitHub repos
--    live under, with how many published systems each holds — counted in the
--    database, never exposing a draft or a masked client.
-- 3. PublicPlatformPulse (§3.2, the "control room") — the platform reporting on
--    itself: audit events, business rules the database enforces, the last
--    successful job and GitHub sync. Aggregates only: no rows, no actors.

-- ---------------------------------------------------------------- titles
CREATE TABLE "TitleKind" (
  "id"        text PRIMARY KEY,
  "key"       text NOT NULL UNIQUE,
  "label"     text NOT NULL,
  "active"    boolean NOT NULL DEFAULT true,
  "createdAt" timestamptz(3) NOT NULL DEFAULT now(),
  "updatedAt" timestamptz(3) NOT NULL DEFAULT now()
);

CREATE TABLE "ProfileTitle" (
  "id"          text PRIMARY KEY,
  "profileId"   integer NOT NULL DEFAULT 1 REFERENCES "Profile"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "kindId"      text NOT NULL REFERENCES "TitleKind"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "label"       text NOT NULL,
  -- Where it's held, e.g. the institution of a qualification.
  "detail"      text,
  -- The education entry behind a qualification, when there is one.
  "educationId" text REFERENCES "Education"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  "sortOrder"   integer NOT NULL DEFAULT 0,
  "startsOn"    date,
  "endsOn"      date,
  "createdAt"   timestamptz(3) NOT NULL DEFAULT now(),
  "updatedAt"   timestamptz(3) NOT NULL DEFAULT now(),
  CONSTRAINT "ProfileTitle_label_present" CHECK (length(btrim("label")) BETWEEN 1 AND 120),
  CONSTRAINT "ProfileTitle_detail_length" CHECK ("detail" IS NULL OR length(btrim("detail")) BETWEEN 1 AND 160),
  CONSTRAINT "ProfileTitle_dates_ordered" CHECK ("startsOn" IS NULL OR "endsOn" IS NULL OR "endsOn" >= "startsOn")
);
CREATE INDEX "ProfileTitle_profileId_sortOrder_idx" ON "ProfileTitle" ("profileId", "sortOrder");

-- Current titles only: started (or undated) and not yet ended, of an active kind.
CREATE VIEW "PublicProfileTitle" AS
 SELECT t."id", k."key" AS "kind", k."label" AS "kindLabel", t."label", t."detail", t."sortOrder", t."startsOn"
   FROM "ProfileTitle" t
   JOIN "TitleKind" k ON k."id" = t."kindId"
  WHERE k."active"
    AND (t."startsOn" IS NULL OR t."startsOn" <= current_date)
    AND (t."endsOn" IS NULL OR t."endsOn" >= current_date);

-- ---------------------------------------------------------------- homes
CREATE TABLE "OrganizationKind" (
  "id"        text PRIMARY KEY,
  "key"       text NOT NULL UNIQUE,
  "label"     text NOT NULL,
  "active"    boolean NOT NULL DEFAULT true,
  "createdAt" timestamptz(3) NOT NULL DEFAULT now(),
  "updatedAt" timestamptz(3) NOT NULL DEFAULT now()
);

ALTER TABLE "Organization" ADD COLUMN "kindId" text REFERENCES "OrganizationKind"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "Organization_kindId_idx" ON "Organization" ("kindId");

-- Ids are generated by the app (cuid) for rows it creates; seeded rows get a uuid.
INSERT INTO "OrganizationKind" ("id", "key", "label") VALUES
  (gen_random_uuid()::text, 'personal', 'Personal'),
  (gen_random_uuid()::text, 'venture', 'Venture'),
  (gen_random_uuid()::text, 'client', 'Client');

UPDATE "Organization" SET "kindId" = (SELECT "id" FROM "OrganizationKind" WHERE "key" = 'client')
 WHERE "isClient" AND "kindId" IS NULL;
UPDATE "Organization" SET "kindId" = (SELECT "id" FROM "OrganizationKind" WHERE "key" = 'personal')
 WHERE "slug" = 'personal' AND "kindId" IS NULL;
UPDATE "Organization" SET "kindId" = (SELECT "id" FROM "OrganizationKind" WHERE "key" = 'venture')
 WHERE "role" IS NOT NULL AND NOT "isClient" AND "kindId" IS NULL;

-- A GitHub home: an organisation GitHub repos are filed under. Its published
-- systems are those under it or in one of its GitHub accounts, live now
-- (BR-1.13) — a client system counts towards the home it was built in only
-- when the client may be named (BR-1.4).
CREATE VIEW "PublicHome" AS
 SELECT o."id", o."name", o."slug", o."role", k."key" AS "kind", o."githubLogins",
        (SELECT count(*)::int
           FROM "System" s
           LEFT JOIN "Organization" so ON so."id" = s."organizationId"
          WHERE is_live(s."contentStatus", s."publishAt")
            AND (s."clientVisibility" = 'PUBLIC' OR s."clientApproved")
            AND (s."clientVisibility" <> 'ANONYMIZED_ONLY' OR s."nameDisclosureApproved" OR s."organizationId" = o."id")
            AND (s."organizationId" = o."id"
                 OR lower(s."githubOwnerLogin") = ANY (SELECT lower(l) FROM unnest(o."githubLogins") l))
        ) AS "publishedSystems"
   FROM "Organization" o
   LEFT JOIN "OrganizationKind" k ON k."id" = o."kindId"
  WHERE cardinality(o."githubLogins") > 0;

-- ---------------------------------------------------------------- pulse
-- Business rules the database itself enforces: every distinct BR-x.y named in
-- a constraint, a trigger, or the body of one of our functions.
CREATE VIEW "PublicPlatformPulse" AS
 WITH sources AS (
   SELECT c."conname"::text || ' ' || pg_get_constraintdef(c."oid") AS src
     FROM pg_constraint c JOIN pg_namespace n ON n."oid" = c."connamespace"
    WHERE n."nspname" = 'public'
   UNION ALL
   SELECT t."tgname"::text
     FROM pg_trigger t JOIN pg_class r ON r."oid" = t."tgrelid" JOIN pg_namespace n ON n."oid" = r."relnamespace"
    WHERE n."nspname" = 'public' AND NOT t."tgisinternal"
   UNION ALL
   SELECT p."prosrc"
     FROM pg_proc p JOIN pg_namespace n ON n."oid" = p."pronamespace"
    WHERE n."nspname" = 'public' AND p."prolang" = (SELECT "oid" FROM pg_language WHERE "lanname" = 'plpgsql')
 ), rules AS (
   SELECT DISTINCT m[1] || '.' || m[2] AS rule
     FROM sources, regexp_matches(src, 'BR[-_]([0-9]+)[._]([0-9]+)', 'gi') AS m
 )
 SELECT 1 AS "id",
        (SELECT count(*)::int FROM rules) AS "rulesEnforcedByDatabase",
        (SELECT count(*)::int FROM "ActivityLog" WHERE "createdAt" > now() - interval '7 days') AS "auditEventsLast7Days",
        (SELECT count(*)::int FROM "ActivityLog") AS "auditEventsTotal",
        (SELECT max("finishedAt") FROM "JobRun" WHERE "status" = 'SUCCEEDED') AS "lastSuccessfulJobAt",
        (SELECT max("githubSyncedAt") FROM "System") AS "lastGithubSyncAt";

-- ---------------------------------------------------------------- access
REVOKE INSERT, UPDATE, DELETE ON "PublicProfileTitle", "PublicHome", "PublicPlatformPulse" FROM platform_runtime;
GRANT SELECT ON "PublicProfileTitle", "PublicHome", "PublicPlatformPulse" TO platform_public;
-- Lookups are public reference data, like the others (F1.8).
GRANT SELECT ON "TitleKind", "OrganizationKind" TO platform_public;

CREATE TRIGGER "TitleKind_audit"        AFTER INSERT OR UPDATE OR DELETE ON "TitleKind"        FOR EACH ROW EXECUTE FUNCTION audit_row_change();
CREATE TRIGGER "ProfileTitle_audit"     AFTER INSERT OR UPDATE OR DELETE ON "ProfileTitle"     FOR EACH ROW EXECUTE FUNCTION audit_row_change();
CREATE TRIGGER "OrganizationKind_audit" AFTER INSERT OR UPDATE OR DELETE ON "OrganizationKind" FOR EACH ROW EXECUTE FUNCTION audit_row_change();

-- ---------------------------------------------------------------- the owner's titles
-- As the owner stated them (2026-09-30) and as their CV records the
-- qualification (Kurhula_Maluleke_CV_2025-1.docx: North-West University).
INSERT INTO "TitleKind" ("id", "key", "label") VALUES
  (gen_random_uuid()::text, 'role', 'Role'),
  (gen_random_uuid()::text, 'qualification', 'Qualification');

INSERT INTO "ProfileTitle" ("id", "kindId", "label", "detail", "sortOrder")
SELECT gen_random_uuid()::text, k."id", v."label", v."detail", v."sortOrder"
  FROM (VALUES
    ('role', 'Software & AI Engineer', NULL, 0),
    ('qualification', 'Final-year BSc Computer Science & Mathematics student', 'North-West University', 1)
  ) AS v("kind", "label", "detail", "sortOrder")
  JOIN "TitleKind" k ON k."key" = v."kind"
 WHERE EXISTS (SELECT 1 FROM "Profile" WHERE "id" = 1)
   AND NOT EXISTS (SELECT 1 FROM "ProfileTitle");
